### ISSUE TITLE
Is it possible to have time_of_day and day_of_week as context features?

### ISSUE THREAD

**Issue by bjarlestam** [fidelity/mab2rec#35]
Hi, we would like to train a model that adjusts recommendations to a set of user preference features as well as time related features, specifically time of day and day of week. Is that possible to do with mab2rec and if so how? The API seems to be designed to take user features and/or item features.

**Comment by skadio** [comment]
Adding it to user features sounds fitting. Conceptually, every different day or time of the day can be seen as a different user/context.

**Comment by bjarlestam** [comment]
Ok, so in the pipeline.benchmark function for example should I then provide multiple rows for each user in the user_features dataframe or do I need to generate unique user_ids for each user/time of day/day of week combination?

**Comment by skadio** [comment]
I don't think you need IDs _for each_ combination. 

For example, if we have two observations (say day and night, for sake of simplicity) for user A at 8AM and same user user A at 8PM, then just treat each one as a different _context_ with its unique id. 

That is, we only have Interaction_1 and Interaction_2. whereby the first corresponds to the A_8AM and the other A_9PM. Since these are actually the same user (user A), I would expect the context vectors to be somewhat similar BUT any feature that changed from 8AM to 8PM is now in effect (e.g., intra-day interactions that happened between 8AM to 8PM) 

Hope that makes sense, 

Btw, if you use our library, we appreciate a GitHub Start ⭐ to spread the word on open-source

**Comment by bjarlestam** [comment]
Ok, thank you for the clarification! If I understand it correctly then the user_id is just a way to correlate contextual features to the observation.

I'm currently evaluating if mab2rec fits our needs and it seems promising so far. You have my ⭐

**Comment by skadio** [comment]
"user_id is just a way to correlate contextual features to the observation." Exactly, it is just a conceptual thing to denote one row of a "context". Hence, it is totally up to you to define what constitutes a "user" for your application. 

Glad to hear it's promising/useful!
