### ISSUE TITLE
regret metrics

### ISSUE THREAD

**Issue by Akshaysharma29** [fidelity/mab2rec#42]
Hi Team, Thanks for sharing this wonderful library. can you guide me on how to use regret metrics while using MAB?

**Comment by bkleyn** [comment]
Hey @Akshaysharma29 

In the context of multi-armed bandits, regret is typically defined as the difference between the cumulative reward given the optimal decision at each time step and the cumulative reward observed for the selected policy. In practice, we typically do not know the optimal decisions though (otherwise we would just use those). In our implementation we therefore focus on finding policies that maximize the cumulative reward.

**Comment by Akshaysharma29** [comment]
Make sense @bkleyn. Thank you 👍
